#!/usr/bin/env python
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def load(path): return json.loads((ROOT/path).read_text())
p1=load("outputs/phase1b/long_window_report.json"); p2=load("outputs/phase2/sub-001/phase2_report.json"); p3=load("outputs/phase3/sub-002/phase3_report.json"); p4=load("outputs/phase4/sub-002/phase4_report.json"); p5=load("outputs/phase5/sub-001/phase5_report.json"); p6=load("outputs/phase6/sub-001/phase6_report.json"); p7=load("outputs/phase7_smoke/phase7_report.json")
report={"final_status":"ENGINEERING PIPELINE COMPLETE / SCIENTIFIC VALIDATION NOT ESTABLISHED","fixed_three_tier_status":"C. ENGINEERING COMPLETE / SCIENTIFIC NOT PASS","phase1B":{"G1B_EQ":"NOT FULLY VERIFIED","G1B_INT":"NOT FULLY VERIFIED","G1B_LONG":p1["G1B_LONG"],"G1B_SZ":"NOT ASSESSED","mechanistic_replay":p1["mechanistic_replay"],"old_overflow_root_cause":p1["old_overflow_root_cause"]},"phase2":p2,"phase3":p3,"phase4":p4,"phase5":{"engineering_status":p5["engineering_status"],"G5A":p5["G5A"],"G5B":p5["G5B"],"G5C":p5["G5C"],"G5D":p5["G5D"],"rhat_x0_max":p5["rhat_x0_max"]},"phase6":p6,"phase7":p7,"limitations":["Several core scientific gates failed or remain unverified.","Full frozen Phase-7 primary configuration was not executed; Phase-7 results are engineering smoke only.","Generation-era TVB version and original RNG state are unavailable.","VEP stimulation generator has a cvar/kernel coupling-shape inconsistency.","Synthetic validation is not clinical validation."]}
out=ROOT/"outputs/FINAL_PROJECT_REPORT.json"; out.write_text(json.dumps(report,indent=2,ensure_ascii=False))
lines=["# VBT baseline final status","","**ENGINEERING PIPELINE COMPLETE / SCIENTIFIC VALIDATION NOT ESTABLISHED**","","Fixed three-tier status: **C. ENGINEERING COMPLETE / SCIENTIFIC NOT PASS**","",f"- Phase 1B: long-window {p1['G1B_LONG']}; mechanistic replay {p1['mechanistic_replay']}.",f"- Phase 2: feature extraction {p2['G2A_feature_extraction']}; EZ early-recruitment sanity {p2['G2B_dataset_EZ_early_recruitment_sanity']}.",f"- Phase 3: G3B={p3['G3B']}, G3C={p3['G3C']}, G3D={p3['G3D']}, G3E={p3['G3E']}; exact equation equivalence not established.",f"- Phase 4: {p4['G4B_feature_comparison']}; causal null {p4['G4C_true_vs_control_null']}.",f"- Phase 5 smoke: engineering {p5['engineering_status']}; convergence {p5['G5D']} (max R-hat {p5['rhat_x0_max']:.3f}).",f"- Phase 6 dev: descriptive AUROC {p6['auroc']:.3f}, AP {p6['average_precision']:.3f}, permutation p {p6['auroc_p']:.3f}; scientific EZN inference not validated because Phase 5 convergence failed.",f"- Phase 7: {p7['mode']}; {p7['subjects_completed']}/30 complete; scientific gate {p7['scientific_EZN_gate']}.","","Several core scientific gates failed or remain unverified. The frozen full primary benchmark remains separate and unexecuted; smoke results cannot be promoted to primary evidence."]
(ROOT/"outputs/FINAL_PROJECT_REPORT.md").write_text("\n".join(lines)+"\n"); print(json.dumps(report,indent=2,ensure_ascii=False))
